apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.namespace.name }}
spec: 
  # Scale할 ReplicaSet 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.metadata.name }}
  minReplicas: 1
  maxReplicas: 5

  # Scale 
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

  