apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.metadata.name }}-http
  namespace: {{ .Values.namespace.name }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.ingress.host }}.{{ .Values.ingress.domain }}`) && PathPrefix(`/modi-dignosis/graphql`, `/modi-dignosis/query`)
      kind: Rule
      middlewares:
        - name: svc-redirect-https
      services:
        - name: {{ .Values.metadata.name }}
          port: {{ .Values.ingress.targetHttp }}

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.metadata.name }}-https
  namespace: {{ .Values.namespace.name }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.host }}.{{ .Values.ingress.domain }}`) && PathPrefix(`/modi-dignosis/graphql`, `/modi-dignosis/query`)
      kind: Rule
      middlewares:
        - name: svc-headers
      services:
        - name: {{ .Values.metadata.name }}
          port: {{ .Values.ingress.targetHttp }}
  # tls:
  #   certResolver: default
