apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
  - name: http
    port: {{ .Values.service.http }}
    protocol: TCP
    targetPort: {{ .Values.service.targetHttp }}
  selector:
    app: {{ .Values.metadata.name }}