apiVersion: v1
kind: Service
metadata:
  name: webrtc-mesh
  namespace: app
  labels:
    app: webrtc-mesh
spec:
  ports:
    - port: 8081
  selector:
    app: webrtc-mesh
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webrtc-mesh
  namespace: app
  labels:
    app: webrtc-mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webrtc-mesh
  template:
    metadata:
      labels:
        app: webrtc-mesh
    spec:
      containers:
        - name: webrtc-mesh
          image: leedu/webrtc_mesh:latest
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          ports:
            - containerPort: 8081
